# Development Version
server:
  port: 8081

#Database Connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_auth_app?useSSL=false&serverTimezone=UTC
    username: root
    password: Sayan@CSE2004@Sayan
#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 6
#      connection-timeout: 1000000
#      idle-timeout: 6000000
#      max-lifetime: 18000000
#      validation-timeout: 18000000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1



  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

# JPA and Hibernate Configuration

logging:
  level:
    org.springframework.security: DEBUG


# Jwt Security Related Configuration
security:
  jwt:
    secret: ${JWT_SECRET:iryhgferysgf,uegfaewgf9icjva2ecrd8yvuejgdqgrfqewfurqeyjgrfquk}
    issuer: ${JWT_ISSUER:myauthapp.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:86400}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}



